"""create ease_bookings

Revision ID: 69190c7684a3
Revises:
Create Date: 2026-08-14 19:11:52.386382
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "69190c7684a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ease_bookings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("trip_type", sa.String(length=32), nullable=False),
        sa.Column("pickup_location", sa.String(length=120), nullable=False),
        sa.Column("destination", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration_days", sa.SmallInteger(), nullable=False),
        sa.Column("passengers", sa.SmallInteger(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "duration_days >= 1 AND duration_days <= 30",
            name="ease_bookings_duration_days_range",
        ),
        sa.CheckConstraint(
            "passengers >= 1 AND passengers <= 14",
            name="ease_bookings_passengers_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ease_bookings_created_at_idx", "ease_bookings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ease_bookings_email"), "ease_bookings", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_ease_bookings_reference"), "ease_bookings", ["reference"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ease_bookings_reference"), table_name="ease_bookings")
    op.drop_index(op.f("ix_ease_bookings_email"), table_name="ease_bookings")
    op.drop_index("ease_bookings_created_at_idx", table_name="ease_bookings")
    op.drop_table("ease_bookings")
    # ### end Alembic commands ###
