"""ops console: users, drivers, refresh tokens, booking events and status

Revision ID: 8d3cb417b3ea
Revises: 69190c7684a3
Create Date: 2026-08-15 10:38:55.679882

Additive and reversible. `ease_bookings` already holds live rows, so every
column added to it is either nullable or carries a server default; nothing here
rewrites or drops existing data.

Two corrections to what autogenerate produced, both of which would have failed
against a non-empty table:

* `updated_at` was emitted as NOT NULL with no default, which cannot be added
  to a table that already has rows. It is added nullable, backfilled from
  `created_at` (the honest value: nothing has updated those bookings yet), then
  tightened to NOT NULL. The server default is dropped afterwards so the column
  matches the model, which sets it in Python via `onupdate`.
* The foreign key was emitted unnamed, so `downgrade()` called
  `op.drop_constraint(None, ...)` and could never run. It is named here.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Spelled out rather than imported from `app.domain.booking_status`. A migration
# is a frozen record of what the schema became at this revision; importing the
# live enum would let a status added next month silently rewrite the meaning of
# this one, and replaying history would then produce a different database.
BOOKING_STATUS_CHECK = (
    "status IN ('new', 'matched', 'confirmed', 'in_progress', 'completed', 'cancelled')"
)

BOOKING_EVENT_TYPE_CHECK = (
    "event_type IN ('created', 'status_changed', 'driver_assigned', "
    "'driver_unassigned', 'note_added', 'viewed')"
)

revision: str = "8d3cb417b3ea"
down_revision: str | None = "69190c7684a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ease_drivers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("vetting_status", sa.String(length=16), nullable=False),
        sa.Column("vehicle_make", sa.String(length=60), nullable=True),
        sa.Column("vehicle_model", sa.String(length=60), nullable=True),
        sa.Column("vehicle_plate", sa.String(length=16), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "vetting_status IN ('pending', 'verified', 'rejected')",
            name="ease_drivers_vetting_status_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ease_drivers_vetting_status_idx",
        "ease_drivers",
        ["vetting_status"],
        unique=False,
    )
    op.create_table(
        "ease_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "failed_login_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('ops', 'admin')", name="ease_users_role_valid"),
        sa.CheckConstraint(
            "failed_login_count >= 0", name="ease_users_failed_login_count_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ease_users_email"), "ease_users", ["email"], unique=True)
    op.create_table(
        "ease_refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["ease_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ease_refresh_tokens_family_id_idx",
        "ease_refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        "ease_refresh_tokens_user_id_idx",
        "ease_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ease_refresh_tokens_token_hash"),
        "ease_refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "ease_booking_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            BOOKING_EVENT_TYPE_CHECK,
            name="ease_booking_events_event_type_valid",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["ease_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"], ["ease_bookings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ease_booking_events_booking_id_created_at_idx",
        "ease_booking_events",
        ["booking_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ease_booking_events_created_at"),
        "ease_booking_events",
        ["created_at"],
        unique=False,
    )
    op.add_column(
        "ease_bookings",
        sa.Column("status", sa.String(length=16), server_default="new", nullable=False),
    )
    op.add_column(
        "ease_bookings", sa.Column("assigned_driver_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "ease_bookings",
        sa.Column("internal_notes", sa.String(length=2000), nullable=True),
    )

    # Three-step, because the table is not empty. See the module docstring.
    op.add_column(
        "ease_bookings",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute(
        "UPDATE ease_bookings SET updated_at = created_at WHERE updated_at IS NULL"
    )
    op.alter_column("ease_bookings", "updated_at", nullable=False)

    op.create_index(
        "ease_bookings_status_created_at_idx",
        "ease_bookings",
        ["status", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "ease_bookings_assigned_driver_id_fkey",
        "ease_bookings",
        "ease_drivers",
        ["assigned_driver_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_check_constraint(
        "ease_bookings_status_valid",
        "ease_bookings",
        BOOKING_STATUS_CHECK,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ease_bookings_status_valid", "ease_bookings", type_="check")
    op.drop_constraint(
        "ease_bookings_assigned_driver_id_fkey", "ease_bookings", type_="foreignkey"
    )
    op.drop_index("ease_bookings_status_created_at_idx", table_name="ease_bookings")
    op.drop_column("ease_bookings", "updated_at")
    op.drop_column("ease_bookings", "internal_notes")
    op.drop_column("ease_bookings", "assigned_driver_id")
    op.drop_column("ease_bookings", "status")
    op.drop_index(
        op.f("ix_ease_booking_events_created_at"), table_name="ease_booking_events"
    )
    op.drop_index(
        "ease_booking_events_booking_id_created_at_idx",
        table_name="ease_booking_events",
    )
    op.drop_table("ease_booking_events")
    op.drop_index(
        op.f("ix_ease_refresh_tokens_token_hash"), table_name="ease_refresh_tokens"
    )
    op.drop_index("ease_refresh_tokens_user_id_idx", table_name="ease_refresh_tokens")
    op.drop_index("ease_refresh_tokens_family_id_idx", table_name="ease_refresh_tokens")
    op.drop_table("ease_refresh_tokens")
    op.drop_index(op.f("ix_ease_users_email"), table_name="ease_users")
    op.drop_table("ease_users")
    op.drop_index("ease_drivers_vetting_status_idx", table_name="ease_drivers")
    op.drop_table("ease_drivers")
    # ### end Alembic commands ###
